In [88]:
from matplotlib import pyplot as plt
import numpy as np
from scipy.constants import N_A, epsilon_0, k

In [89]:
C_0=0.13
sub=np.array(['toluen',
'para ksylen',
'meta ksylen',
'orto ksylen',
'chlorobenzen',
'chloroform'])
C=np.array([0.27,
0.25,
0.26,
0.28,
0.55,
0.59])
n=np.array([1.4969,
1.4938,
1.4939,
1.5018,
1.5199,
1.4419])
M=np.array([92.14,
106.16,
106.16,
106.16,
112.56,
119.38])
M=M*0.001
rho=np.array([0.8623,
0.8565,
0.8598,
0.8755,
1.1058,
1.4788])
eps_pk=2.27
T=298

In [90]:
eps=(eps_pk*(C-C_0)-(C-C[1]))/(C[1]-C_0)
eps

array([2.48166667, 2.27      , 2.37583333, 2.5875    , 5.445     ,
       5.86833333])

In [91]:
P_m=(eps-1)*M/((eps+2)*rho)
#P_m=P_m*1000000 #[m^3/mol]
P_m

array([0.03532651, 0.03686459, 0.03882116, 0.04196067, 0.06077354,
       0.04994818])

In [92]:
R=((n**2-1)*M)/((n**2+2)*rho)
#R=R*1000000    #[m^3/mol]
R

array([0.03126234, 0.036071  , 0.03593874, 0.03577233, 0.03094024,
       0.02135562])

In [93]:
mu=(9*epsilon_0*k*T*(P_m-R)/N_A)**(1/2)  #[C*m]
mu_D=mu/(3.33564*10**(-30))              #[D]
mu, mu_D

(array([4.70388030e-29, 2.07857973e-29, 3.96140022e-29, 5.80439380e-29,
        1.27444359e-28, 1.24766058e-28]),
 array([14.1018824 ,  6.23142703, 11.87598247, 17.40113981, 38.20686858,
        37.40393399]))