In [1]:
from matplotlib import pyplot as plt
import numpy as np
from scipy.constants import N_A, epsilon_0, k

In [2]:
C_0=0.13
sub=np.array(['toluen',
'para ksylen',
'meta ksylen',
'orto ksylen',
'chlorobenzen',
'chloroform'])
C=np.array([0.27,
0.25,
0.26,
0.28,
0.55,
0.59])
n=np.array([1.4969,
1.4938,
1.4939,
1.5018,
1.5199,
1.4419])
M=np.array([92.14,
106.16,
106.16,
106.16,
112.56,
119.38])
M=M/1000
rho=np.array([0.8623,
0.8565,
0.8598,
0.8755,
1.1058,
1.4788])
rho=rho*1000
eps_pk=2.27
T=298

In [3]:
eps=(eps_pk*(C-C_0)-(C-C[1]))/(C[1]-C_0)
eps

array([2.48166667, 2.27      , 2.37583333, 2.5875    , 5.445     ,
       5.86833333])

In [4]:
P_m=(eps-1)*M/((eps+2)*rho)
P_m

array([3.53265138e-05, 3.68645883e-05, 3.88211614e-05, 4.19606702e-05,
       6.07735439e-05, 4.99481824e-05])

In [5]:
R=((n**2-1)*M)/((n**2+2)*rho)
#R=R*1000000    #[m^3/mol]
R

array([3.12623365e-05, 3.60710033e-05, 3.59387395e-05, 3.57723346e-05,
       3.09402400e-05, 2.13556234e-05])

In [6]:
mu=(9*epsilon_0*k*T*(P_m-R)/N_A)**(1/2)  #[C*m]
mu_D=mu/(3.33564*10**(-30))              #[D]
mu, mu_D

(array([1.48749756e-30, 6.57304623e-31, 1.25270474e-30, 1.83551048e-30,
        4.03014450e-30, 3.94544919e-30]),
 array([0.44594068, 0.19705502, 0.37555154, 0.55027236, 1.20820727,
        1.18281625]))

In [12]:
mu_lit=np.array([0.39,0.02,0.30,0.59,1.56,1.15])
proc=abs(mu_D-mu_lit)/mu_lit*100

proc, np.mean(proc), np.mean(np.delete(proc, 1))

(array([ 14.34376328, 885.27512433,  25.18384686,   6.73349882,
         22.55081604,   2.85358683]),
 159.49010602694227,
 14.3331023669465)